/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Profile {
  'bio' : string,
  'title' : string,
  'socialLinks' : Array<SocialLink>,
  'name' : string,
  'skills' : Array<string>,
}
export interface Project {
  'id' : ProjectId,
  'title' : string,
  'featured' : boolean,
  'description' : string,
  'githubUrl' : [] | [string],
  'imageUrl' : string,
  'category' : string,
  'liveUrl' : [] | [string],
  'techStack' : Array<string>,
}
export type ProjectId = bigint;
export interface SocialLink { 'url' : string, 'platform' : string }
export type Timestamp = bigint;
export interface _SERVICE {
  'addProject' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      [] | [string],
      [] | [string],
      string,
      boolean,
    ],
    ProjectId
  >,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'setProfile' : ActorMethod<[Profile], undefined>,
  'submitContact' : ActorMethod<[string, string, string], bigint>,
  'updateProject' : ActorMethod<[Project], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];