/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProjectId = IDL.Nat;
export const Project = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'description' : IDL.Text,
  'githubUrl' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'liveUrl' : IDL.Opt(IDL.Text),
  'techStack' : IDL.Vec(IDL.Text),
});
export const Timestamp = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const SocialLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'socialLinks' : IDL.Vec(SocialLink),
  'name' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Bool,
      ],
      [ProjectId],
      [],
    ),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
  'setProfile' : IDL.Func([Profile], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateProject' : IDL.Func([Project], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProjectId = IDL.Nat;
  const Project = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'description' : IDL.Text,
    'githubUrl' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'liveUrl' : IDL.Opt(IDL.Text),
    'techStack' : IDL.Vec(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const SocialLink = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'socialLinks' : IDL.Vec(SocialLink),
    'name' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Bool,
        ],
        [ProjectId],
        [],
      ),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], ['query']),
    'setProfile' : IDL.Func([Profile], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateProject' : IDL.Func([Project], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };